blog:
  title: Blog
  banner:
    title: Warning
    content: The blog will be down tomorrow.
file:
  upload-dir: ./assets
spring:
  output:
    ansi:
      enabled: always
logging:
  level:
    root: warn
    com.example.myblog: debug
